### ISSUE TITLE
Applications Overview Icon Overlapping For higher Resolution monitors (FIX Included)

### ISSUE THREAD

**Issue by DrJfrost** [daniruiz/flat-remix-gnome#187]
The current theme's CSS file fails to show correctly the applications overview menu on higher resolution monitors (such as 4k or 2k resolutions) and as a result displays incorrectly the menu along with enlarged icons:

![image](https://user-images.githubusercontent.com/26847284/126239648-f2c446ed-5fa5-41dc-92b6-bf83b3f8389f.png)

The solution is to correctly specify the ` -shell-grid-horizontal-item-size` and `-shell-grid-vertical-item-size` properties thus allowing the icons and the label to correctly adjust according to the screen size.

```css

/* App Grid */
.icon-grid {
  row-spacing: 12px;
  column-spacing: 12px;
  max-row-spacing: 72px;
  max-column-spacing: 72px;
  page-padding-top: 24px;
  page-padding-bottom: 24px;
  page-padding-left: 12px;
  page-padding-right: 12px; 
  -shell-grid-horizontal-item-size: 136px; /* added this line */
  -shell-grid-vertical-item-size: 136px; /* added this line */
}
``` 

Final Result:
A clean menu that fits Icons according to the screen without overlapping the label, (on search results it also gets better responsiveness)
![image](https://user-images.githubusercontent.com/26847284/126239477-8decee3d-afdc-4292-bf4b-2c29ab7b990b.png)
