### ISSUE TITLE
How to make dock transparent in Flat Remix Blue Dark

### ISSUE THREAD

**Issue by ba32107** [daniruiz/flat-remix-gnome#208]
Hi! I just updated to Jammy Jellyfish, so I downloaded the latest version of my usual theme, Flat Remix Blue Dark. Everything looks great, but the dock is completely transparent, which I don't like. I tried modifying `gnome.css` by playing with the `background-color` property in this class:

```CSS
.dash-background {
  background-color: #323643;
  border-radius: 28px;
  padding: 12px;
  spacing: 6px;
  margin-bottom: 12px; }
```

But no matter what I try, the opacity does not change. Can you please help? What class in this CSS I should be tweaking?

Filename: `01-Flat-Remix-Blue-20220622.tar.xz` and I'm using the `Flat-Remix-Blue-Dark-fullPanel` theme.

Thanks!
